name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@v3.34  # Use the latest version
        with:
          token: ${{ secrets.METRICS_SECRET }}
          user: Dimiqhz
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: true
          config_timezone: Europe/Moscow
          config_twemoji: true
          plugin_calendar: yes
          plugin_calendar_limit: 0
          plugin_languages: true
          plugin_languages_indepth: true
          plugin_languages_categories: markup, programming
          plugin_leetcode: true
          plugin_leetcode_user: Dimiqhz
          plugin_leetcode_sections: solved
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

      - name: Commit and Push Metrics
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📈 Update GitHub metrics [skip ci]"
          branch: metrics  # Specify the branch where metrics are stored
          file_pattern: './metrics/**'  # Adjust this based on where metrics are generated
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_SECRET }}
